### ISSUE TITLE
Hitting 'Done' after placing a Flat Sign on a glowstone block causes 'Internal Server Error'

### ISSUE THREAD

**Issue by BlindByrd** [Myrathi/FlatSignsEx#2]
FTB Unleashed 1.0.3

**Comment by Myrathi** [comment]
`1.0.3` isn't available on the launcher, so I cannot test it.
The issue **cannot** be reproduced in the working, available versions, though (`1.1.0` and `1.1.1`).

Only suggestion I have is that you update your pack.

Marking `invalid` and closing, as it cannot be reproduced in existing (publicly available) packs or in-dev. Sorry.
