### ISSUE TITLE
Crash in 1.6.2 and 1.6.4 when used with the Better Signs mod

### ISSUE THREAD

**Issue by Lathanael** [Myrathi/FlatSignsEx#4]
I was trying the BetterSigns mod(http://www.minecraftforum.net/topic/1837653-) in 1.5.2. While it was not working 100% with FlatSigns it did not crash: http://puu.sh/4JVkU

Now with 1.6.x If both are installed it crashes (1.6.4 report): http://pastebin.com/xLZ9TfdM
FS doesn't crash when Better Signs is not installed.

Is there anything you could do to fix this?

**Comment by Myrathi** [comment]
BetterSigns goes for a heavy-handed "replace 3 entire classes with its own" plus more. There's no straight-forward way to fix it short of straight-up doubling the amount of code already in FS.

Sorry but this is a `wontfix` :\
